CREATE TABLE measure (
MeasureID text primary key,
ProgramName text not null,
YearQuarter text not null,
Sector text not null,
DeliveryType text not null,
BuildingType text not null,
ClimateZone text not null,
GasSavingsProfile text,
GasSector text,
MeasureElectricEndUseShape text,
TargetSector text,
MeasureApplicationType text not null,
MeasureCode text,
MeasureDescription text not null,
MeasureImpactType text not null,
MeasureID text,
TechnologyGroup text,
TechnologyType text not null,
UseCategory text,
UseSubCategory text not null,
PreviousMeasureDescription text,
StandardMeasureDescription text,
WorkPaperDescription text,
WorkPaperVersion text,
NormUnit text not null,
NumUnits numeric not null,
UnitkW1stBaseline numeric not null,
UnitkWh1stBaseline numeric not null,
UnitTherm1stBaseline numeric not null,
UnitkW2ndBaseline numeric not null,
UnitkWh2ndBaseline numeric not null,
UnitTherm2ndBaseline numeric not null,
UnitMeaCost1stBaseline numeric not null,
UnitMeaCost2ndBaseline numeric not null,
UnitDirectInstallLab numeric,
UnitDirectInstallMat numeric,
UnitEndUserRebate numeric,
UnitIncentiveToOthers numeric,
NTG_ID text,
NTGRkW numeric not null,
NTGRkWh numeric not null,
NTGRTherm numeric not null,
NTGRCost numeric not null,
EUL_ID text,
EUL_Yrs numeric not null,
RUL_ID text,
RUL_Yrs numeric not null,
GSIA_ID text,
RealizationRatekW numeric not null,
RealizationRatekWh numeric not null,
RealizationRateTherm numeric not null,
InstallationRatekW numeric not null,
InstallationRatekWh numeric not null,
InstallationRateTherm numeric not null,
MarketEffectsBenefits numeric,
MarketEffectsCosts numeric,
RateScheduleElec text,
RateScheduleGas text,
CombustionType text,
MeasInflation numeric
Residential_Flag bit,
Upstream_Flag bit);
