CREATE TABLE measure (
	CEInputID text primary key,
	PrgID text not null,
	ClaimYearQuarter text not null,
	Sector text not null,
	DeliveryType text not null,
	BldgType text not null,
	E3ClimateZone text not null,
	E3GasSavProfile text,
	E3GasSector text,
	E3MeaElecEndUseShape text,
	E3TargetSector text,
	MeasAppType text not null,
	MeasCode text,
	MeasDescription text not null,
	MeasImpactType text not null,
	MeasureID text,
	TechGroup text,
	TechType text not null,
	UseCategory text,
	UseSubCategory text not null,
	PreDesc text,
	StdDesc text,
	SourceDesc text,
	Version text,
	NormUnit text not null,
	NumUnits numeric not null,
	UnitkW1stBaseline numeric not null,
	UnitkWh1stBaseline numeric not null,
	UnitTherm1stBaseline numeric not null,
	UnitkW2ndBaseline numeric not null,
	UnitkWh2ndBaseline numeric not null,
	UnitTherm2ndBaseline numeric not null,
	UnitMeaCost1stBaseline numeric not null,
	UnitMeaCost2ndBaseline numeric not null,
	UnitDirectInstallLab numeric,
	UnitDirectInstallMat numeric,
	UnitEndUserRebate numeric,
	UnitIncentiveToOthers numeric,
	NTG_ID text,
	NTGRkW numeric not null,
	NTGRkWh numeric not null,
	NTGRTherm numeric not null,
	NTGRCost numeric not null,
	EUL_ID text,
	EUL_Yrs numeric not null,
	RUL_ID text,
	RUL_Yrs numeric not null,
	GSIA_ID text,
	RealizationRatekW numeric not null,
	RealizationRatekWh numeric not null,
	RealizationRateTherm numeric not null,
	InstallationRatekW numeric not null,
	InstallationRatekWh numeric not null,
	InstallationRateTherm numeric not null,
	Residential_Flag bit,
	Upstream_Flag bit,
	PA text not null,
	MarketEffectsBenefits numeric,
	MarketEffectsCosts numeric,
	RateScheduleElec text,
	RateScheduleGas text,
	CombustionType text,
	MeasInflation numeric,
	FirstYear text not null);
